import json
from openai import OpenAI

client = OpenAI()

SYSTEM_PROMPT = """
You are a professional career consultant.
Write concise, high-quality English cover letters for global tech companies.
"""

USER_PROMPT = """
Generate a cover letter in valid YAML format:

cover:
  company:
  position:
  opening:
  why_me:
  experience:
    - ...
    - ...
  closing:

Rules:
- Professional and concise
- Frontend-focused
- No generic filler text

Input:
{input_json}
"""


def generate_cover_yaml(llm_input: dict) -> str:
    response = client.chat.completions.create(
        model="gpt-4.1-mini",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {
                "role": "user",
                "content": USER_PROMPT.format(
                    input_json=json.dumps(llm_input, indent=2)
                ),
            },
        ],
        temperature=0.4,
    )

    content = response.choices[0].message.content
    if content is None:
        raise RuntimeError("LLM response content is None")
    if not content.strip().startswith("cover:"):
        raise ValueError("Invalid YAML generated by LLM")

    return content